#!/bin/bash
rm -rf $(ls | egrep -v 'Dockerfile|Makefile|boilerplate.go.txt|config|docker-compose.yml|scripts')
apiserver-boot init repo --domain aipg.intel.com
apiserver-boot create group version resource --group nserv --version v1 --kind Cluster
apiserver-boot build generated
cp config/cluster_types pkg/apis/nserv/v1/cluster_types.go
cp config/cluster_sample sample/cluster.yaml
cp config/vimrc $HOME/.vimrc
cp config/bash_profile $HOME/.bash_profile
cp scripts/v* /usr/local/bin
apiserver-boot build generated
apiserver-boot build executables --generate=false

echo go build -o bin/apiserver -gcflags "-N -l" cmd/apiserver/main.go
go build -o bin/apiserver -gcflags "-N -l" cmd/apiserver/main.go
echo go build -o bin/controller-manager -gcflags "-N -l" cmd/controller-manager/main.go
go build -o bin/controller-manager -gcflags "-N -l" cmd/controller-manager/main.go
