#!/bin/bash
scripts/clean
apiserver-boot init repo --domain aipg.intel.com
apiserver-boot create group version resource --group nserv --version v1 --kind Cluster
apiserver-boot build generated
cp config/cluster_types pkg/apis/nserv/v1/cluster_types.go
cp config/cluster_sample sample/cluster.yaml

case "$HOME" in
  /root)
    cp config/vimrc $HOME/.vimrc
    cp config/gdbinit $HOME/.gdbinit
    cp config/bash_profile $HOME/.bash_profile
    cp scripts/v* /usr/local/bin
    ;;
  *)
    ;;
esac

apiserver-boot build generated
apiserver-boot build executables --generate=false
echo go build -o bin/apiserver -gcflags "-N -l" cmd/apiserver/main.go
go build -o bin/apiserver -gcflags "-N -l" cmd/apiserver/main.go
echo go build -o bin/controller-manager -gcflags "-N -l" cmd/controller-manager/main.go
go build -o bin/controller-manager -gcflags "-N -l" cmd/controller-manager/main.go
